program: main.c effect.c helpers.c mouse.c particle.c fps.c def.h -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
	gcc main.c effect.c helpers.c mouse.c particle.c fps.c def.h -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o main
